import type { MaintenancePlan } from "./types";

export const basePlans: MaintenancePlan[] = [
  {
    id: "essential",
    name: "Essential",
    priceMonthly: 119,
    squareFootageRange: "0-1,500 SF",
    description: "Condos and small homes. Quarterly inspections and essential maintenance tasks.",
    features: [
      "Quarterly property inspection",
      "Gutter cleaning and inspection",
      "HVAC filter replacement",
      "Plumbing fixture inspection",
      "Electrical safety check",
      "Documentation and photos",
      "Route-aware scheduling",
    ],
    audience: "residential",
    ctaLabel: "Start Essential Plan",
    active: true,
  },
  {
    id: "standard",
    name: "Standard",
    priceMonthly: 149,
    squareFootageRange: "1,501-2,500 SF",
    description: "Average family homes. Comprehensive maintenance for typical residential properties.",
    features: [
      "All Essential features",
      "Bi-annual deep inspection",
      "Exterior maintenance review",
      "Roof and flashing inspection",
      "Crawlspace/attic inspection",
      "Water heater flush",
      "Smoke detector testing",
      "Extended documentation",
    ],
    audience: "residential",
    ctaLabel: "Start Standard Plan",
    active: true,
  },
  {
    id: "premium",
    name: "Premium",
    priceMonthly: 179,
    squareFootageRange: "2,501-3,500 SF",
    description: "Larger residential properties. Enhanced coverage for homes with more systems.",
    features: [
      "All Standard features",
      "Quarterly deep inspection",
      "Full systems review",
      "Deck and patio inspection",
      "Appliance maintenance check",
      "Seasonal preparation",
      "Route-aware urgent-condition review",
      "Comprehensive reporting",
    ],
    audience: "residential",
    ctaLabel: "Start Premium Plan",
    active: true,
  },
  {
    id: "estate",
    name: "Estate",
    priceMonthly: 219,
    squareFootageRange: "3,501+ SF",
    description: "Large-scale residential properties. Complete maintenance coverage for estate homes.",
    features: [
      "All Premium features",
      "Monthly property walk-through",
      "Full estate systems review",
      "Landscape coordination",
      "Pool/spa system inspection",
      "Guest quarters maintenance",
      "Planned access and route notes",
      "Custom maintenance calendar",
    ],
    audience: "residential",
    ctaLabel: "Start Estate Plan",
    active: true,
  },
];
