import type { ServiceCard } from "./types";

export const baseServices: ServiceCard[] = [
  {
    id: "inspection-repairs",
    title: "Inspection Repairs",
    summary:
      "Clear inspection flags with practical repairs. We address the list, document the work, and provide completion photos.",
    href: "/services/inspection-repairs",
    ctaLabel: "Request Inspection Repair",
    serviceType: "inspection-repairs",
    tags: ["Inspections", "Repairs", "Documentation"],
    displayOrder: 1,
    active: true,
  },
  {
    id: "water-mold-moisture",
    title: "Water, Mold & Moisture",
    summary:
      "Water intrusion investigation, dry-out, and moisture control. We identify sources, document findings, and provide clear scopes.",
    href: "/services/water-damage",
    ctaLabel: "Request Moisture Assessment",
    serviceType: "water-mold-moisture",
    tags: ["Water Damage", "Mold", "Moisture Control"],
    displayOrder: 2,
    active: true,
  },
  {
    id: "window-door-replacements",
    title: "Window & Door Replacements",
    summary: "Practical replacement work for drafty, damaged, leaking, or inspection-flagged windows and doors.",
    href: "/services/window-door-replacement",
    ctaLabel: "Request Window or Door Replacement",
    serviceType: "window-door-replacements",
    tags: ["Windows", "Doors", "Weather Protection"],
    displayOrder: 3,
    active: true,
  },
  {
    id: "maintenance-plans",
    title: "Maintenance Plans",
    summary:
      "Scheduled maintenance that keeps properties in good condition. Clear scopes, documented work, completed on schedule.",
    href: "/plans",
    ctaLabel: "View Maintenance Plans",
    serviceType: "maintenance-plans",
    tags: ["Preventive", "Scheduled", "Documentation"],
    displayOrder: 4,
    active: true,
  },
  {
    id: "emergency-response",
    title: "Emergency Response",
    summary:
      "Emergency repair intake for active conditions. Requests are reviewed for safety, access, photos, location, and route timing before work is scheduled.",
    href: "/services/emergency-response",
    ctaLabel: "Request Emergency Service",
    serviceType: "emergency-response",
    tags: ["Emergency", "Urgent", "Active Conditions"],
    displayOrder: 5,
    active: true,
  },
  {
    id: "energy-weatherization",
    title: "Energy & Weatherization",
    summary:
      "Practical weatherization work for high-desert wind, freeze exposure, draft control, and documented property protection.",
    href: "/services/energy-weatherization",
    ctaLabel: "Request Weatherization Assessment",
    serviceType: "energy-weatherization",
    tags: ["Energy", "Weatherization", "Insulation"],
    displayOrder: 6,
    active: true,
  },
  {
    id: "property-preservation",
    title: "Property Preservation",
    summary:
      "Vacant property maintenance and preservation. Secure, document, and maintain properties during transitions.",
    href: "/services/property-preservation",
    ctaLabel: "Request Preservation Service",
    serviceType: "property-preservation",
    tags: ["Vacant Properties", "Preservation", "Security"],
    displayOrder: 7,
    active: true,
  },
  {
    id: "residential-remodeling",
    title: "Residential Remodeling",
    summary: "Practical remodeling work for kitchens, bathrooms, and living spaces. Clear scopes, documented work.",
    href: "/services/residential-remodeling",
    ctaLabel: "Request Remodeling Consultation",
    serviceType: "residential-remodeling",
    tags: ["Kitchens", "Bathrooms", "Remodeling"],
    displayOrder: 8,
    active: true,
  },
  {
    id: "commercial-maintenance",
    title: "Commercial Maintenance",
    summary: "Planned maintenance and repair support for offices, storefronts, and working commercial facilities.",
    href: "/services/commercial-maintenance",
    ctaLabel: "Request Commercial Maintenance",
    serviceType: "commercial-maintenance",
    tags: ["Commercial", "Facilities", "Maintenance"],
    displayOrder: 9,
    active: true,
  },
  {
    id: "church-nonprofit-maintenance",
    title: "Church / Non-Profit Facility Maintenance",
    summary: "Maintenance support for churches and non-profit facilities with practical scheduling and facility care.",
    href: "/services/church-nonprofit-maintenance",
    ctaLabel: "Request Facility Maintenance",
    serviceType: "church-nonprofit-maintenance",
    tags: ["Churches", "Non-Profits", "Facility Care"],
    displayOrder: 10,
    active: true,
  },
];
